# Generated by Django 5.2 on 2025-05-11 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0002_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
