# Generated by Django 5.2 on 2025-05-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0003_delete_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='usergroup',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Employee', 'Employee')], max_length=100),
        ),
    ]
