# Generated by Django 4.2 on 2025-09-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0008_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='check_in',
            new_name='clock_in',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='check_out',
            new_name='clock_out',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='hours_worked',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='Absent', max_length=20),
        ),
    ]
