# Generated by Django 4.2 on 2025-09-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0009_rename_check_in_attendance_clock_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='hours_worked',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Late', 'Late'), ('Half Day', 'Half Day'), ('Absent', 'Absent')], default='Absent', max_length=20),
        ),
    ]
