# Generated by Django 4.2 on 2025-09-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0011_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
                ('holiday_type', models.CharField(choices=[('common', 'Common Leave'), ('company', 'Company Leave')], max_length=20)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
