# Generated by Django 4.2 on 2025-10-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0015_alter_profile_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='usergroup',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Employee', 'Employee')], max_length=100),
        ),
    ]
