# Generated by Django 4.2 on 2025-10-13 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0018_employee_profile_alter_employee_blood_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='profile',
        ),
        migrations.AlterField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(help_text='Example: A+, B-, O+', max_length=5),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid emergency number.', regex='^\\+?\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
