# Generated by Django 4.2 on 2025-10-13 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0019_remove_employee_profile_alter_employee_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employee_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='hrm_app.employee'),
        ),
    ]
