# Generated by Django 4.2 on 2025-10-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0020_profile_employee_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='employee_profile',
        ),
    ]
