# Generated by Django 5.2.6 on 2025-11-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0023_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='required_role',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('employee', 'Employee and above'), ('admin', 'Admin and above'), ('superadmin', 'Super Admin only')], default='everyone', max_length=20),
        ),
    ]
