# Generated by Django 5.2.6 on 2025-11-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0024_module_is_active_module_order_module_required_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.CharField(max_length=100, unique=True)),
                ('menu_label', models.CharField(max_length=100)),
                ('employee_access', models.BooleanField(default=True)),
                ('admin_access', models.BooleanField(default=True)),
                ('superadmin_access', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'menu_label'],
            },
        ),
    ]
