# Generated by Django 5.2.6 on 2025-11-14 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0025_menupermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuPermission',
        ),
        migrations.RemoveField(
            model_name='module',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='module',
            name='order',
        ),
        migrations.RemoveField(
            model_name='module',
            name='required_role',
        ),
    ]
